/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TdmcustomSearch {
        "propValue": string;
        "searchFor": string;
    }
}
declare global {
    interface HTMLTdmcustomSearchElement extends Components.TdmcustomSearch, HTMLStencilElement {
    }
    var HTMLTdmcustomSearchElement: {
        prototype: HTMLTdmcustomSearchElement;
        new (): HTMLTdmcustomSearchElement;
    };
    interface HTMLElementTagNameMap {
        "tdmcustom-search": HTMLTdmcustomSearchElement;
    }
}
declare namespace LocalJSX {
    interface TdmcustomSearch {
        "propValue"?: string;
        "searchFor"?: string;
    }
    interface IntrinsicElements {
        "tdmcustom-search": TdmcustomSearch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tdmcustom-search": LocalJSX.TdmcustomSearch & JSXBase.HTMLAttributes<HTMLTdmcustomSearchElement>;
        }
    }
}
